// Generated by CoffeeScript 1.9.0
var calc1plus2, calc3plus4, plusWithMsg, say;

say = function(msg) {
  return console.log(this.name + " say '" + msg + "'");
};


/*
 * call
 */

say.call({
  name: "よつば"
}, "いいわけはじごくできく(call)");


/*
 * apply
 */

say.apply({
  name: "よつば"
}, ["いいわけはじごくできく(apply)"]);


/*
 * bindする関数
 */

plusWithMsg = function(msg) {
  return console.log("Message: " + this.name + " " + msg + " " + this.a + " + " + this.b + " = " + (this.a + this.b));
};

calc1plus2 = plusWithMsg.bind({
  name: "よつば",
  a: 1,
  b: 2
}, "が計算します（bind）...");

calc1plus2();

calc3plus4 = plusWithMsg.bind({
  name: "よつば",
  a: 3,
  b: 4
}, "が計算します（bind）...");

calc3plus4();
