// Generated by CoffeeScript 1.9.0
var onReady, promise;

promise = (function() {
  return new Promise(function(resolve, reject) {
    switch (document.readyState) {
      case "interactive":
      case "complete":
        console.log("loaded!!!");
        return resolve();
      default:
        console.log("loading...");
        return window.addEventListener("DOMContentLoaded", resolve);
    }
  });
})();

onReady = function() {
  return console.log("=== DOM COMPLETE ===");
};

promise.then(onReady);

console.log("=== STARTING ===");
