// Generated by CoffeeScript 1.9.0
(function() {
  var btn, onFullfilled, onRejected, taskA, taskB, taskC;
  taskA = function() {
    var msg;
    msg = "TaskA Error";
    console.log(msg);
    throw new Error(msg);
  };
  taskB = function() {
    return console.log("TaskB Completed");
  };
  taskC = function() {
    return console.log("TaskC Completed");
  };
  onRejected = function(err) {
    return console.log("onRejected: " + err);
  };
  onFullfilled = function() {
    return console.log("onFullfilled");
  };
  btn = document.getElementById("run");
  return btn.addEventListener("click", function() {
    var promise;
    promise = Promise.resolve();
    return promise.then(taskA).then(taskB)["catch"](onRejected).then(onFullfilled);
  });
})();
